### ISSUE TITLE
plecost missing distribution

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#285]
plecost 1.0.1-2 fails to running because of a missing distribution.
Currently running on archlinux 4.9.8-1 x86_64 with Python 3.6.0
```
Traceback (most recent call last):
  File "/usr/bin/plecost", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'plecost==1.0.1' distribution was not found and is required by the application
````

**Comment by Cthulu201** [comment]
Fixed.
