### ISSUE TITLE
bbqsql missing gevent Semaphore

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#286]
bbqsql fails to launch because of a missing dep
Currently running on archlinux 4.9.8-1 x86_64 with Python 2.7.13
```
Traceback (most recent call last):
  File "/usr/bin/bbqsql", line 3, in <module>
    from bbqsql import *
  File "/usr/lib/python2.7/site-packages/bbqsql/__init__.py", line 30, in <module>
    from lib import *
  File "/usr/lib/python2.7/site-packages/bbqsql/lib/__init__.py", line 1, in <module>
    import api
  File "/usr/lib/python2.7/site-packages/bbqsql/lib/api.py", line 3, in <module>
    from .technique import *
  File "/usr/lib/python2.7/site-packages/bbqsql/lib/technique.py", line 8, in <module>
    from gevent.coros import Semaphore
ImportError: No module named coros
```

**Comment by archey** [comment]
Pushed patch to bbqsql, package is rebuilding now

**Comment by Wh1t3Fox** [comment]
Tested and working

**Comment by kalovskitim** [comment]
Is there a solution now?
