### ISSUE TITLE
bdfproxy fails to work

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#290]
community/mitmproxy 1.0.2-1 is installed 

```
Traceback (most recent call last):
  File "bdf_proxy.py", line 34, in <module>
    from mitmproxy import controller, proxy, platform
ImportError: No module named mitmproxy

```

**Comment by xorond** [comment]
The dependency `community/mitmproxy` is for python3, while the package requires a python2 version of mitmproxy.

**Comment by archey** [comment]
lets see what the last py2 version of mitmproxy is and build it.

**Comment by archey** [comment]
This will require a build of mitmproxy v0.18.2 

https://github.com/mitmproxy/mitmproxy/releases/tag/v0.18.2

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/e94dea24d53a113db0318a98e5d3c39709b1a3ed

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/155929ed0a0e08e219bd0e9bd45e34756b393021

```
Traceback (most recent call last):
  File "bdf_proxy.py", line 34, in <module>
    from mitmproxy import controller, proxy, platform
  File "/usr/lib/python2.7/site-packages/mitmproxy/proxy/__init__.py", line 3, in <module>
    from .config import ProxyConfig
  File "/usr/lib/python2.7/site-packages/mitmproxy/proxy/config.py", line 16, in <module>
    from netlib.http import authentication
  File "/usr/lib/python2.7/site-packages/netlib/http/__init__.py", line 2, in <module>
    from netlib.http.request import Request
  File "/usr/lib/python2.7/site-packages/netlib/http/request.py", line 10, in <module>
    from netlib.http import multipart
ImportError: cannot import name multipart
```
