### ISSUE TITLE
webscarab fails to start

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#300]
Currently running on archlinux 4.9.8-1 x86_64
```
No plugins found!
Using WebScarab.whitelistRegex pattern : . Will not save any data for requests not matching this pattern
org.owasp.webscarab.ui.swing.EnabledBooleanTableCellRenderer[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.BorderUIResource$CompoundBorderUIResource@6bfcc2a1,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=javax.swing.plaf.InsetsUIResource[top=2,left=2,bottom=2,right=2],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=]
Help set not found
10:42:12 main(Proxy.parseListenerConfig): No proxies configured!?
java.net.UnknownHostException: archstrike: archstrike: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1496)
	at org.owasp.webscarab.plugin.proxy.SSLSocketFactoryFactory.<clinit>(SSLSocketFactoryFactory.java:51)
	at org.owasp.webscarab.plugin.proxy.Proxy.<init>(Proxy.java:122)
	at org.owasp.webscarab.WebScarab.loadAllPlugins(WebScarab.java:189)
	at org.owasp.webscarab.WebScarab.main(WebScarab.java:131)
	at org.owasp.webscarab.Main.main(Main.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.net.UnknownHostException: archstrike: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1492)
	... 11 more
10:42:12 main(SSLSocketFactoryFactory.<init>): Generating CA key
java.lang.NullPointerException
	at org.bouncycastle.x509.X509V3CertificateGenerator.setIssuerDN(Unknown Source)
	at org.owasp.webscarab.util.SunCertificateUtils.sign(SunCertificateUtils.java:73)
	at org.owasp.webscarab.plugin.proxy.SSLSocketFactoryFactory.generateCA(SSLSocketFactoryFactory.java:206)
	at org.owasp.webscarab.plugin.proxy.SSLSocketFactoryFactory.<init>(SSLSocketFactoryFactory.java:111)
	at org.owasp.webscarab.plugin.proxy.SSLSocketFactoryFactory.<init>(SSLSocketFactoryFactory.java:83)
	at org.owasp.webscarab.plugin.proxy.Proxy.<init>(Proxy.java:123)
	at org.owasp.webscarab.WebScarab.loadAllPlugins(WebScarab.java:189)
	at org.owasp.webscarab.WebScarab.main(WebScarab.java:131)
	at org.owasp.webscarab.Main.main(Main.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)

```

**Comment by comrumino** [comment]
Removed webscarab in favor of owasp-zap.
