### ISSUE TITLE
fern-wifi-cracker missing QtWebKit

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#301]
Currently running on archlinux 4.9.8-1 x86_64 
pyqt4-common 4.12-4, python-pyqt4 4.12-4,and python2-pyqt4 4.12-4 are installed

````
Traceback (most recent call last):
  File "./execute.py", line 73, in <module>
    from core import *
  File "/usr/share/fern-wifi-cracker/core/fern.py", line 15, in <module>
    from wep import *
  File "/usr/share/fern-wifi-cracker/core/wep.py", line 2, in <module>
    from core.tools import*
  File "/usr/share/fern-wifi-cracker/core/tools.py", line 6, in <module>
    from gui.geotrack import *
  File "/usr/share/fern-wifi-cracker/gui/geotrack.py", line 211, in <module>
    from PyQt4 import QtWebKit
ImportError: cannot import name QtWebKit
```

**Comment by archey** [comment]
Closing as this is referenced in a grouped issue, of upsteam "fixes" 

https://github.com/ArchStrike/ArchStrike/issues/278
