### ISSUE TITLE
bettercap fails to work

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#363]
```
/usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap/spoofers/icmp.rb:24:in `<class:ICMPRedirectPacket>': uninitialized constant PacketFu::EthHeaderMixin (NameError)
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap/spoofers/icmp.rb:17:in `<module:Spoofers>'
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap/spoofers/icmp.rb:15:in `<module:BetterCap>'
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap/spoofers/icmp.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap.rb:56:in `block in bettercap_autoload'
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap.rb:55:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap.rb:55:in `bettercap_autoload'
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/lib/bettercap.rb:60:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/bettercap-1.6.0/bin/bettercap:19:in `<top (required)>'
	from /usr/bin/bettercap:22:in `load'
	from /usr/bin/bettercap:22:in `<main>'
```

This might have something to do with the `ruby-packetfu` version provided by upstream AL repositories. Continuation of #358

**Comment by Cthulu201** [comment]
Fixed
