### ISSUE TITLE
Update empire to 2.3

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#394]
When empire is updated to new source, we get
```
Traceback (most recent call last):
  File "empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/usr/share/empire/lib/common/empire.py", line 28, in <module>
    import agents
  File "/usr/share/empire/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/usr/share/empire/lib/common/encryption.py", line 62, in <module>
    random_function = OpenSSL.rand.bytes
AttributeError: 'module' object has no attribute 'rand'
```
when trying to run empire. Fix this issue and update source.

**Comment by vloup** [comment]
OpenSSL.rand.bytes got removed in pyopenssl 17.3.0, they suggest to use os.random() instead.

**Comment by vloup** [comment]
Actually, the dev branch of empire does have the proper fix.
