### ISSUE TITLE
updating empire to 2.5

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#400]
some problems arise:

```
$ empire
Traceback (most recent call last):
  File "empire", line 1393, in <module>
    main = empire.MainMenu(args=args)
  File "/usr/share/empire/lib/common/empire.py", line 84, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
  File "/usr/share/empire/lib/common/helpers.py", line 554, in get_config
    cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
sqlite3.OperationalError: no such table: config
```

```
$ empire-setup
Empire DB found...
Would you like to reset your Empire DB [y/N]y

 [>] Enter server negotiation password, enter for random generation: 
Traceback (most recent call last):
  File "./setup_database.py", line 62, in <module>
    conn = sqlite3.connect('/usr/share/empire/data/empire.db'%INSTALL_PATH)
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "./empire", line 1393, in <module>
    main = empire.MainMenu(args=args)
  File "/usr/share/empire/lib/common/empire.py", line 84, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
  File "/usr/share/empire/lib/common/helpers.py", line 554, in get_config
    cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
sqlite3.OperationalError: no such table: config
```

**Comment by comrumino** [comment]
Fixed

**Comment by xorond** [comment]
@comrumino

**Comment by comrumino** [comment]
Updated
