### ISSUE TITLE
pyinstaller depends on `python-dis3` which doesn't exist

### ISSUE THREAD

**Issue by doronbehar** [ArchStrike/ArchStrike#426]
I get this error after installing `pyinstaller`:

```
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3123, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3107, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3136, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dis3' distribution was not found and is required by PyInstaller
```
`pacman -Ss python-dis3` gives nothing and `pip search dis3` does:
```
dis3 (0.1.2)  - Python 2.7 backport of the "dis" module from Python 3.5+
```

**Comment by xorond** [comment]
thanks, i'm taking a look

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/6ccc9444304cf1f4263a1b5cc9fa5f5c4c65920c
i updated pyinstaller to latest version, which supports python3.7
with the upcoming deprecation of python2 it looked like the smarter option to switch to python3 altogether.
the problem should be fixed now, and `dis3` shouldn't be required as it's a backport and only needed for python2.
`pacman -Syyu` to update please.
