### ISSUE TITLE
[Tool request] ViperMonkey

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#453]
https://github.com/decalage2/ViperMonkey

**Comment by Cthulu201** [comment]
python-vipermonkey-git added. Please test, and reopen if errors are encountered. Cheers!

**Comment by vdun** [comment]
thx.
Here is an error:
```
# vbashell -h
Traceback (most recent call last):
  File "/usr/bin/vbashell", line 11, in <module>
    load_entry_point('vipermonkey==0.8', 'console_scripts', 'vbashell')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/vipermonkey/__init__.py", line 3, in <module>
    from vipermonkey.api import *
  File "/usr/lib/python3.8/site-packages/vipermonkey/api.py", line 48, in <module>
    from vipermonkey.core import deobfuscation
  File "/usr/lib/python3.8/site-packages/vipermonkey/core/__init__.py", line 100, in <module>
    from logger import log
ModuleNotFoundError: No module named 'logger'
```

**Comment by Cthulu201** [comment]
Sorry for the delay in replying. This is an odd error since logger.py is within the package. When you're running it on Arch, at what point do you receive this error? Thanks.
